# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tQNL5nMeww_dEw-J1cIYLl7PVuIBaUe
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('Pyspark').getOrCreate()

spark

df=spark.read.csv('/amazon.csv',header=True, inferSchema=True)

df.show(3)

df.printSchema()

df.columns

df.count()

len(df.columns)

df.describe()

df.describe().show()

df.toPandas()['month'].unique()

len(df.toPandas()['month'].unique())

df.show()

df.select('year').show()

df.select(['year','date','month']).show()

df.withColumn('new_number',df.number+1).show()

df=df.withColumn('new_number',df.number+1)

df.show()

df.withColumnRenamed('state','state_area').show()

df.filter(df['new_number']>5.0).show()

df.filter(df['new_number']>5.0).select('year').show()

df.filter((df['new_number']>5.0) & (df['month']=='Janeiro')).select('year').show()

df.groupby('new_number').mean().show()

df.orderBy(df['new_number']).show()

df.orderBy(df['new_number'].desc()).show()

from pyspark.sql.functions import mean

mean1=df.select(mean(df['new_number'])).collect()

mean1[0][0]

df.fillna(mean1[0][0]).show()

